# Generated by Django 5.0.1 on 2024-01-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_contacts_options_alter_dealer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='letter',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='building letter'),
        ),
    ]
