# Generated by Django 5.0.1 on 2024-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_contacts_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='contacts',
        ),
        migrations.AddField(
            model_name='dealer',
            name='building',
            field=models.IntegerField(blank=True, null=True, verbose_name='building number'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='country',
            field=models.CharField(max_length=60, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='house',
            field=models.IntegerField(verbose_name='house number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='letter',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='building letter'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='street',
            field=models.CharField(max_length=100, verbose_name='street'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
