# Generated by Django 5.0.1 on 2024-01-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_dealer_contacts_dealer_building_dealer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendors.dealer'),
        ),
    ]
