# Generated by Django 5.0.1 on 2024-01-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_dealer_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='vendors.product'),
        ),
    ]
