# Generated by Django 5.0.1 on 2024-01-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_dealer_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_type',
            field=models.CharField(choices=[('fac', 'factory'), ('ret', 'retail network'), ('ind', 'individual entrepreneur')], default=1, max_length=3, verbose_name='dealer type'),
            preserve_default=False,
        ),
    ]
