# Generated by Django 5.0.1 on 2024-01-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_dealer_dealer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='debt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='debt'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendors.dealer', verbose_name='contractor'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='vendors.product', verbose_name='products'),
        ),
    ]
